# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestCountryPickerFramework' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod ‘CountryPicker’, :path => '../CountryPicker.podspec'
  #pod ‘CountryPicker’, :git => ‘https://github.com/SURYAKANTSHARMA/CountryPicker/’, :tag => ‘1.0.5’
  # Pods for TestCountryPickerFramework

end
