# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'TestCountryPickerFramework' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SKCountryPicker' '~> 1.2.0'
end
