# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestCountryPickerFramework' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod ‘CountryPicker’, :path => '/Users/suryakantsharma/Desktop/CountryPicker/CountryPicker.podspec'

  target 'TestCountryPickerFrameworkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestCountryPickerFrameworkUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
