# Uncomment the next line to define a global platform for your project
# platform :ios, '15.0'

target 'CountryPicker13+Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'SKCountryPicker', :git => 'https://github.com/SURYAKANTSHARMA/CountryPicker', :branch => 'iOS15AndAbove'

   #pod 'SKCountryPicker', path: '../'
  # Pods for CountryPicker13+Example

end
